version: "3.6"
services:
  hydra-admin:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUILD_TYPE: docker
    ports:
      - "3000:80"
    depends_on:
      - hydra
    links:
      - hydra
    environment:
      # See https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
      # This is needed to avoide some openssl switcheridoo in node 17
      NODE_OPTIONS: --openssl-legacy-provider


      HYDRA_PROXY_URL: "http://hydra:4445"
      PORT: 3000

    networks:
    - gateway
    - auth_stack
    labels:
      